### ISSUE TITLE
Program does not work after installation.

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [kusti8/RPi-chromium#8]
I installed the Chrome plugin, then I installed the rest of the program following the instructions used in the `README.md` file found at the bottom of the page.  It doesn't work, no matter if I have the TBOPlayer (OMXPlay GUI) open or not.  I press the extract video and no matter how many times I press it I get n response at all from the plugin other than that I have pressed the button .  What should I try to do next?  I am not so sure if this software is even being checked on.

**Comment by kusti8** [comment]
I haven't been developing this project for a while now. With the release of
hardware acceleration, there wasn't too much of a reason. Gkreidl has an
alternative.

**Comment by CoWinkKeyDinkInc** [comment]
Where would I find this alternative?  Could you share me the link please?

**Comment by CoWinkKeyDinkInc** [comment]
@kusti8 So where would I find the alternative, I tried searching for it but I can't find it, could you send me a link please?

**Comment by kusti8** [comment]
Install omxplayergui. Then use this
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=163018

**Comment by CoWinkKeyDinkInc** [comment]
thanks!
